### ISSUE TITLE
soft_label 是做什么用的？

### ISSUE THREAD

**Issue by helloword12345678** [lonePatient/daguan_2019_rank9#3]
感谢分享，请问soft_label 是做什么用的？

**Comment by lonePatient** [comment]
@helloword12345678 其实就是在计算end_fc那里是使用标签还是使用标签预测概率

**Comment by xilinniao123** [comment]
![image](https://user-images.githubusercontent.com/11830865/65818696-919bb680-e246-11e9-96f8-870ca8f03557.png)
关于您这里的span 方式抽取，每个位置其实是一个多分类，依旧无法解决嵌套输出问题吧？

**Comment by lonePatient** [comment]
@hitxujian 不要太注重我这里的使用方式，这个是对达观数据的实验，正常来说span模式能解决大部分嵌套问题，至少我目前遇到的。
