### ISSUE TITLE
crf部分start_tag/end_tag 是否重复计算了？

### ISSUE THREAD

**Issue by LifangD** [lonePatient/daguan_2019_rank9#5]
感谢开源~ 有一个问题请教，crf部分 score_sencetence  pad 了start 和stop 以及 forward 部分 都额外计算 了start和stop tag， 但bert处理的时候已经把这两个tag 放进了句子序列里。请问是特意处理的还是？

**Comment by heroazhe** [comment]
score_sentence是已知tag计算分数，跟forward的不是一回事吧
